context:
  version: "1.30.1"

package:
  name: lightningcss
  version: ${{ version }}

source:
  url: https://github.com/parcel-bundler/lightningcss/archive/v${{ version }}.tar.gz
  sha256: 234c9c3ef0d8d59252cf64f36b53f49c8ca9d937f5301e501227c08ea4b6b7fe

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - lightningcss --help

about:
  license: MPL-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: An extremely fast CSS parser, transformer, bundler, and minifier written in Rust.
  homepage: https://github.com/parcel-bundler/lightningcss
  repository: https://github.com/parcel-bundler/lightningcss

extra:
  recipe-maintainers:
    - danielnachun
